### ISSUE TITLE
works, but file size much bigger than the original one

### ISSUE THREAD

**Issue by leewi9** [hwding/pdf-unstamper#5]
why is that??

![image](https://user-images.githubusercontent.com/10832544/52620027-57132280-2ede-11e9-9823-7f61988f8fd2.png)

**Comment by hwding** [comment]
@leewi9 Thanks for feedback, plz provide your unstamper **version** and **arguments**, better with the raw pdf file link you mentioned above.

**Comment by leewi9** [comment]
unstamper version 0.2.1

original file http://file.allitebooks.com/20150519/Understanding%20Linux%20Network%20Internals.pdf

and command is 
`java -jar pdf-unstamper.jar -i path1 -o path2 -k www.allitebooks.com`

**Comment by hwding** [comment]
@leewi9 This issue has been fixed, according to the file you provided, its size goes from 8153KB to 8141KB, with arguments `java -jar unstamper.jar -i 0.pdf -k www.allitebooks.com -o 00.pdf -c`, be aware of the `-c` option if there's a frame you want to remove surrounding the textual watermark.

This fix will be provided in the next release.

Thank u for the feedback again.

**Comment by leewi9** [comment]
great,  but another issue still exists, seems the hyperlink still there

![image](https://user-images.githubusercontent.com/10832544/52636084-935a7900-2f06-11e9-93f7-c65400d96e09.png)

**Comment by hwding** [comment]
@leewi9 Yep, try use `-c` to remove the frame along with the link.
